 GRANT ALL PRIVILEGES ON DATABASE evdiag TO evuser;
 GRANT ALL ON SCHEMA public TO evuser;
 ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO evuser;
 ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO evuser;